x = str("Hello World")
x = int(20)
x = float(20.5)
x = complex(1j)
x = list(("apple", "bannana", "cherry"))
x = tuple(("apple", "bannana", "cherry"))
x = range(6)
x = dict(name="John", age=36)
x = set(("apple", "bannana", "cherry"))
x = frozenset(("apple", "bannana", "cherry"))
x = bool(5)
x = bytes(5)
x = bytearray(5)
x = memoryview(bytes(5))
